from __future__ import annotations

from typing import Protocol


class GitLabClientPort(Protocol):
    async def get_user(self, token: str) -> dict: ...
    async def list_groups(self, token: str) -> list[dict]: ...
    async def list_group_projects(self, token: str, group_id: int) -> list[dict]: ...
    async def list_project_pipelines(self, token: str, project_id: int) -> list[dict]: ...
